# Generated by Django 3.1.7 on 2021-03-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yathra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=150)),
                ('review', models.TextField(default=None)),
                ('storyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='yathra.story')),
            ],
        ),
    ]
